apiVersion: apps/v1
kind: Deployment
metadata:
  name: brm-api-deployment
  creationTimestamp: null
  labels:
    app: brm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brm-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: brm-api
    spec:
      containers:
        - image: {{ .Values.container.image }}
          name: {{ .Values.container.name }}
          envFrom:
            - configMapRef:
                name: brm-api-configmap
          resources:
            limits:
              cpu: 2
              memory: "4Gi"
            requests:
              cpu: 1
              memory: "2Gi"
          ports:
            - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
status: { }
